ChatCo:
  version: ${project.version}
  chatPrefixes:
    aqua: true
    black: true
    blue: true
    bold: true
    dark_aqua: true
    dark_blue: true
    dark_gray: true
    dark_green: true
    dark_purple: true
    dark_red: true
    gold: true
    gray: true
    green: true
    italic: true
    light_purple: true
    magic: true
    red: true
    strikethrough: true
    underline: true
    yellow: true
  chatColors:
    aqua: true
    black: true
    blue: true
    bold: true
    dark_aqua: true
    dark_blue: true
    dark_gray: true
    dark_green: true
    dark_purple: true
    dark_red: true
    gold: true
    gray: true
    green: true
    italic: true
    light_purple: true
    magic: true
    red: true
    strikethrough: true
    underline: true
    white: true
    yellow: true