name: release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Git
        uses: actions/checkout@v4

      - name: Java
        uses: actions/setup-java@v5.7.0
        with:
          java-version: '21'
          distribution: 'temurin'
          check-latest: true

      - name: Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Package
        run: ./gradlew build --stacktrace

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          body: 'automated release at commit ${{ github.sha }}'
          draft: false
          prerelease: false
          files: build/libs/ChatCoPlus-*.jar
